In [6]:
import numpy as np
from numpy import linalg as LA

A = np.array([[1, 2, 3], 
              [4,5,6], 
              [7,8,9]])

autovalores, autovetores = LA.eig(A)
print("Lista de autovalores: \n", autovalores)  
print('')
print("Lista de autovetores: \n", autovetores)
print('')
C = autovetores[:,0]*autovalores[0]
print(C)

Lista de autovalores: 
 [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

Lista de autovetores: 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

[ -3.73863537  -8.46653421 -13.19443305]


In [ ]:
def gauss_seidel(a, b, vetorSolucao, iteracoes):
  iteracao = 0
  while iteracao < iteracoes:
    for i in range(len(a)):
      x = b[i]
      for j in range(len(a)):
        if i != j:
          x -= a[i][j]*vetorSolucao[j]
      x/=a[i][j]
      vetorSolucao[i] = x
    iteracao += 1
  
  print(vetorSolucao)

In [5]:
#Copiar a matriz
Q = autovetores
#Criar a inversa da matriz
R = LA.inv(Q)
#Criar a matriz Diagonal a partir da lista de autovalores
L = np.diag(autovalores)
print('aa',L)
#Reconstruir a matriz original a
B = Q.dot(L).dot(R)
print('bb',B)


aa [[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.30367773e-15]]
bb [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
